[package]
name = "apexsky_dma"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
apexsky = { path = "../apexsky" }
apexsky_kmbox = { path = "../apexsky_kmbox" }
async-trait = "0.1.80"
bitset = "0.1.2"
bitset-core = "0.1.1"
chrono = "0.4.38"
#console-subscriber = "0.1.5"
dataview = "1.0.1"
rand = "0.8.5"
include-flate = "0.3.0"
indexmap = { version = "2.2.6", features = ["serde"] }
intptr = { version = "0.1.6", features = ["dataview_1", "serde"] }
memflow = "0.2.1"
memflow-qemu = { git = "https://github.com/memflow/memflow-qemu", rev = "78bdf30" }
memflow-win32 = "0.2.0"
memprocfs = "5.9.13"
named_constants = "0.2.0"
ndarray = "0.15.6"
obfstr = "0.4.3"
once_cell = "1.19.0"
parking_lot = { version = "0.12.2", features = ["arc_lock", "nightly", "owning_ref", "serde"] }
pe-parser = "0.5.1"
prost = "0.12.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
tokio = { version = "1.37.0", features = ["full"] }
tonic = { version = "0.11.0", features = ["zstd", "gzip"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["json", "chrono", "env-filter"] }
tracing-appender = "0.2.3"
futures-util = "0.3.30"


[build-dependencies]
tonic-build = "0.11.0"
